<a href="https://colab.research.google.com/github/Muhammad-Taufiq-Khan/CKD/blob/main/Imputation_OutlierRemoving_Scalling_(Accuracy_99_max).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [109]:
import pandas as pd #Data Manioulation

url = 'https://raw.githubusercontent.com/Muhammad-Taufiq-Khan/CKD/main/ckd.csv'
dataframe = pd.read_csv(url)
dataframe.head(3)

id   age    bp    sg   al   su  ...   dm cad appet  pe  ane  classification
0   0  48.0  80.0  1.02  1.0  0.0  ...  yes  no  good  no   no             ckd
1   1   7.0  50.0  1.02  4.0  0.0  ...   no  no  good  no   no             ckd
2   2  62.0  80.0  1.01  2.0  3.0  ...  yes  no  poor  no  yes             ckd

[3 rows x 26 columns]

In [110]:
#Rename Each Column
dataframe.columns = ["id","age", "blood_pressure", "specific_gravety", "albumin","sugar" ,"red_blood_cells", "pus_cell", "pus_cell_clumps", "bacteria", "blood_glucose_random", "blood _urea", "serum_creatinine", "sodium", "potassium", "hemoglobine", "packed_cell_volume", "white_blood_cell_count", "red_blood_cell_count", "hypertension", "diabetes_mellitias", "coronary_artery_disease", "appetite", "pedal_edema", "anemia", "ckd" ]
#To Rename Particular column
# df.rename(columns = {'test':'TEST'}, inplace = True) 

#drop id
dataframe.drop(['id'], axis = 1, inplace=True)

#show top 3 record or sample
dataframe.head(3)


age  blood_pressure  specific_gravety  ...  pedal_edema  anemia  ckd
0  48.0            80.0              1.02  ...           no      no  ckd
1   7.0            50.0              1.02  ...           no      no  ckd
2  62.0            80.0              1.01  ...           no     yes  ckd

[3 rows x 25 columns]

In [111]:
#Show Unique values per Attribute
for i in (dataframe):
  print(f"Attribute Name: {i}   Total Unique Value: {dataframe[i].nunique()} \n Unique Values: {dataframe[i].unique()}\n")




Attribute Name: age   Total Unique Value: 76 
 Unique Values: [48.  7. 62. 51. 60. 68. 24. 52. 53. 50. 63. 40. 47. 61. 21. 42. 75. 69.
 nan 73. 70. 65. 76. 72. 82. 46. 45. 35. 54. 11. 59. 67. 15. 55. 44. 26.
 64. 56.  5. 74. 38. 58. 71. 34. 17. 12. 43. 41. 57.  8. 39. 66. 81. 14.
 27. 83. 30.  4.  3.  6. 32. 80. 49. 90. 78. 19.  2. 33. 36. 37. 23. 25.
 20. 29. 28. 22. 79.]

Attribute Name: blood_pressure   Total Unique Value: 10 
 Unique Values: [ 80.  50.  70.  90.  nan 100.  60. 110. 140. 180. 120.]

Attribute Name: specific_gravety   Total Unique Value: 5 
 Unique Values: [1.02  1.01  1.005 1.015   nan 1.025]

Attribute Name: albumin   Total Unique Value: 6 
 Unique Values: [ 1.  4.  2.  3.  0. nan  5.]

Attribute Name: sugar   Total Unique Value: 6 
 Unique Values: [ 0.  3.  4.  1. nan  2.  5.]

Attribute Name: red_blood_cells   Total Unique Value: 2 
 Unique Values: [nan 'normal' 'abnormal']

Attribute Name: pus_cell   Total Unique Value: 2 
 Unique Values: ['normal' 'abnormal' na

**Check attributes with single value and duplicate records**

In [112]:
#Delete attributes with single column
print("#Delete attributes with single column")
counts = dataframe.nunique()
single_attributes = [i for i,v in enumerate(counts) if v == 1]
print(f"List of single attribute: {single_attributes}")
dataframe.drop(single_attributes, axis=1, inplace=True)

print("\n")

#Delete Duplicate samples
print("#Delete Duplicate samples")
# calculate duplicates
dups = dataframe.duplicated()
# report if there are any duplicates
print(f"Is there any duplicate sample: {dups.any()}")
# list all duplicate rows
print(f"list all duplicate rows: {dataframe[dups]}")

#Delete attributes with single column
List of single attribute: []


#Delete Duplicate samples
Is there any duplicate sample: False
list all duplicate rows: Empty DataFrame
Columns: [age, blood_pressure, specific_gravety, albumin, sugar, red_blood_cells, pus_cell, pus_cell_clumps, bacteria, blood_glucose_random, blood _urea, serum_creatinine, sodium, potassium, hemoglobine, packed_cell_volume, white_blood_cell_count, red_blood_cell_count, hypertension, diabetes_mellitias, coronary_artery_disease, appetite, pedal_edema, anemia, ckd]
Index: []


### 1. Encoding Categorical Data into Neumerical Form Using Python map() fuction

In [113]:
# Map
dataframe["red_blood_cells"]= dataframe["red_blood_cells"].map({'normal':1,'abnormal':0})

dataframe["pus_cell"]= dataframe["pus_cell"].map({'normal':1,'abnormal':0})

dataframe["pus_cell_clumps"]= dataframe["pus_cell_clumps"].map({'present':1,'notpresent':0})

dataframe["bacteria"]= dataframe["bacteria"].map({'present':1,'notpresent':0})

dataframe["hypertension"]= dataframe["hypertension"].map({'yes':1,'no':0})

dataframe["diabetes_mellitias"]= dataframe["diabetes_mellitias"].map({'yes':1,'no':0,' yes':1, '\tno':0, '\tyes':1})

dataframe["coronary_artery_disease"]= dataframe["coronary_artery_disease"].map({'yes':1,'no':0, '\tno':0})

dataframe["appetite"]= dataframe["appetite"].map({'good':1,'poor':0})

dataframe["pedal_edema"]= dataframe["pedal_edema"].map({'yes':1,'no':0})

dataframe["anemia"]= dataframe["anemia"].map({'yes':1,'no':0})

dataframe["ckd"]= dataframe["ckd"].map({'ckd':1,'ckd\t':1, 'notckd':0})

dataframe.head(10)

age  blood_pressure  specific_gravety  ...  pedal_edema  anemia  ckd
0  48.0            80.0             1.020  ...          0.0     0.0    1
1   7.0            50.0             1.020  ...          0.0     0.0    1
2  62.0            80.0             1.010  ...          0.0     1.0    1
3  48.0            70.0             1.005  ...          1.0     1.0    1
4  51.0            80.0             1.010  ...          0.0     0.0    1
5  60.0            90.0             1.015  ...          1.0     0.0    1
6  68.0            70.0             1.010  ...          0.0     0.0    1
7  24.0             NaN             1.015  ...          1.0     0.0    1
8  52.0           100.0             1.015  ...          0.0     1.0    1
9  53.0            90.0             1.020  ...          0.0     1.0    1

[10 rows x 25 columns]

### 2. Converting Different datatypes into standard Float32 format

In [114]:
#Converting all datatype into float32 in Full Dataframe
#Otherwise KNN Imputation won't work
dataframe = pd.DataFrame({col: dataframe[col].astype('category').cat.codes.astype('float32') for col in dataframe}, index=dataframe.index)
print(dataframe.dtypes)

age                        float32
blood_pressure             float32
specific_gravety           float32
albumin                    float32
sugar                      float32
red_blood_cells            float32
pus_cell                   float32
pus_cell_clumps            float32
bacteria                   float32
blood_glucose_random       float32
blood _urea                float32
serum_creatinine           float32
sodium                     float32
potassium                  float32
hemoglobine                float32
packed_cell_volume         float32
white_blood_cell_count     float32
red_blood_cell_count       float32
hypertension               float32
diabetes_mellitias         float32
coronary_artery_disease    float32
appetite                   float32
pedal_edema                float32
anemia                     float32
ckd                        float32
dtype: object


### 3. Resampling Dataset into Traing & Testing Data

In [115]:
#Splitting data into train test 
X, y = dataframe.drop('ckd', axis = 1), dataframe['ckd']
from sklearn.model_selection import train_test_split #Import Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.33, random_state = 15) #Spliting Dataset Into Training & Testing Data


### 4. Imputing Missing Values of ***Training*** Data using KNN Imputation

In [116]:
# import numpy as np
# Checking dataframe structure as array
# print((dataframe[["age","ckd"]]).to_numpy())

#K-NN Imputation on Training Dataset
from sklearn.impute import KNNImputer #import Knn Imputer
imputer = KNNImputer(n_neighbors = 5) #Declaring that 5 nearest neighbour should be decided
imputer.fit(X_train) #fitting imputer according to Training Features (X_train)

Imputed_X_train = imputer.transform(X_train) #Appling Imputation
Imputed_X_train #Print Imputed Arrary

array([[16.,  3.,  3., ...,  1.,  0.,  0.],
       [48.,  2.,  2., ...,  1.,  0.,  0.],
       [34.,  3.,  3., ...,  1.,  0.,  0.],
       ...,
       [62.,  5.,  2., ...,  1.,  0.,  0.],
       [34.,  2.,  4., ...,  1.,  0.,  0.],
       [40.,  5., -1., ...,  0.,  0.,  0.]], dtype=float32)

In [117]:
#Checking balence between CKD and NotCKD Patient in Training Data
ckd = 0
notckd = 0
for i in y_train:
  if i == 1:
    ckd +=1
  else:
    notckd += 1
print(f"ckd: {ckd},   notckd:{notckd}")

print(f"CKD - NotCKD: {ckd-notckd}")

ckd: 171,   notckd:97
CKD - NotCKD: 74


### 5. Detecting and Removing Outlier from ***Training*** Dataset

In [118]:
from sklearn.neighbors import LocalOutlierFactor

# summarize the shape of the training dataset
print(Imputed_X_train.shape, y_train.shape)

# identify outliers in the training dataset
lof = LocalOutlierFactor(novelty=True)
lof.fit(Imputed_X_train)
yhat = lof.predict(Imputed_X_train)

# select all rows that are not outliers
mask = yhat != -1
Outless_X_train, Outless_y_train = Imputed_X_train[mask, :], y_train[mask]

# summarize the shape of the updated training dataset
print(Outless_X_train.shape, Outless_y_train.shape)

(268, 24) (268,)
(267, 24) (267,)


### 6. Scalling Training Dataset

In [119]:
from sklearn.preprocessing import MinMaxScaler
# define the scaler
scaler = MinMaxScaler()
# fit on the training dataset
scaler.fit(Outless_X_train)
# scale the training dataset
X_train = scaler.transform(Outless_X_train)


### Importing and Loading Classification Algorithms

In [120]:
#Importing Classification Models

from sklearn.naive_bayes import MultinomialNB,GaussianNB
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier


#Training Models
SVCmodel = SVC().fit(X_train, Outless_y_train)
# MNBmodel = MultinomialNB().fit(Imputed_X_train, y_train)
GNBmodel = GaussianNB().fit(X_train, Outless_y_train)
DTmodel = DecisionTreeClassifier().fit(X_train, Outless_y_train)
RFmodel = RandomForestClassifier().fit(X_train, Outless_y_train)
LRmodel = LogisticRegression().fit(X_train, Outless_y_train)
KNNmodel = KNeighborsClassifier(n_neighbors = 5).fit(X_train, Outless_y_train)

# Testing Section

## Imputation on Testing Dataset

### Imputing Missing Values of **Testing** Data using KNN Imputation

In [121]:
#K-NN Imputation on Testing Dataset
Imputed_X_test = imputer.transform(X_test) #Appling Imputation
Imputed_X_test #Print Imputed Arrary

array([[24.,  1.,  4., ...,  1.,  0.,  0.],
       [52.,  4., -1., ...,  1.,  0.,  0.],
       [56.,  2.,  1., ...,  1.,  0.,  0.],
       ...,
       [57.,  2.,  3., ...,  1.,  1.,  0.],
       [59.,  3.,  1., ...,  1.,  1.,  0.],
       [26.,  2., -1., ...,  1.,  0.,  1.]], dtype=float32)

In [122]:
#Balence between CKD and NotCKD Patient in Training Data
ckd = 0
notckd = 0
for i in y_test:
  if i == 1:
    ckd +=1
  else:
    notckd += 1
print(f"ckd: {ckd},   notckd:{notckd}")

print(f"CKD - NotCKD: {ckd-notckd}")

ckd: 79,   notckd:53
CKD - NotCKD: 26


### Evaluating Model After KNN Imputation

In [123]:
# #Evaluating Model

# from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# print(">>>>>>>>>>>>>>     Support Vector Machine     <<<<<<<<<<<<")
# pred = SVCmodel.predict(Imputed_X_test)
# score = accuracy_score(y_test,pred)
# print(score)
# conf = confusion_matrix(y_test,pred)
# print(conf) 
# report = classification_report(y_test,pred)
# print(report)
# print("\n")


# # print(">>>>>>>>>>>>>>     Multinomial Naive Bayes     <<<<<<<<<<<<")
# # pred = MNBmodel.predict(X_test)
# # score = accuracy_score(y_test,pred)
# # print(score)
# # conf = confusion_matrix(y_test,pred)
# # print(conf)
# # report = classification_report(y_test,pred)
# # print(report)
# # print(" ")

# print(">>>>>>>>>>>>>>     Gaussian Naive Bayes     <<<<<<<<<<<<")
# pred = GNBmodel.predict(Imputed_X_test)
# score = accuracy_score(y_test,pred)
# print(score)
# conf = confusion_matrix(y_test,pred)
# print(conf)
# report = classification_report(y_test,pred)
# print(report)
# print(" ")

# print(">>>>>>>>>>>>>>     Decission Tree      <<<<<<<<<<<<")
# pred = DTmodel.predict(Imputed_X_test)
# score = accuracy_score(y_test,pred)
# print(score)
# conf = confusion_matrix(y_test,pred)
# print(conf)
# report = classification_report(y_test,pred)
# print(report)
# print(" ")

# print(">>>>>>>>>>>>>>     Random Forest     <<<<<<<<<<<<")
# pred = RFmodel.predict(Imputed_X_test)
# score = accuracy_score(y_test,pred)
# print(score)
# conf = confusion_matrix(y_test,pred)
# print(conf)
# report = classification_report(y_test,pred)
# print(report)
# print(" ")
# print(">>>>>>>>>>>>>>     Logistic Regression     <<<<<<<<<<<<")
# pred = LRmodel.predict(Imputed_X_test)
# score = accuracy_score(y_test,pred)
# print(score)
# conf = confusion_matrix(y_test,pred)
# print(conf)
# report = classification_report(y_test,pred)
# print(report)
# print(" ")

## Removing Outlier from Testing Dataset

### Removing Outlier from Imputed ***Testing*** Dataset

In [124]:
# summarize the shape of the training dataset
print(Imputed_X_test.shape, y_test.shape)

# identify outliers in the training dataset
# lof = LocalOutlierFactor(novelty=True)
yhat = lof.predict(Imputed_X_test)

# select all rows that are not outliers
mask = yhat != -1
Outless_X_test, Outless_y_test = Imputed_X_test[mask, :], y_test[mask]

# summarize the shape of the updated training dataset
print(Outless_X_test.shape, Outless_y_test.shape)

(132, 24) (132,)
(131, 24) (131,)


### Evaluating Model After Removing Outlier

In [125]:
# #Evaluating Model

# from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# print(">>>>>>>>>>>>>>     Support Vector Machine     <<<<<<<<<<<<")
# pred = SVCmodel.predict(Outless_X_test)
# score = accuracy_score(Outless_y_test,pred)
# print(score)
# conf = confusion_matrix(Outless_y_test,pred)
# print(conf) 
# report = classification_report(Outless_y_test,pred)
# print(report)
# print("\n")


# # print(">>>>>>>>>>>>>>     Multinomial Naive Bayes     <<<<<<<<<<<<")
# # pred = MNBmodel.predict(Outless_X_test)
# # score = accuracy_score(Outless_y_test,pred)
# # print(score)
# # conf = confusion_matrix(Outless_y_test,pred)
# # print(conf)
# # report = classification_report(Outless_y_test,pred)
# # print(report)
# # print(" ")

# print(">>>>>>>>>>>>>>     Gaussian Naive Bayes     <<<<<<<<<<<<")
# pred = GNBmodel.predict(Outless_X_test)
# score = accuracy_score(Outless_y_test,pred)
# print(score)
# conf = confusion_matrix(Outless_y_test,pred)
# print(conf)
# report = classification_report(Outless_y_test,pred)
# print(report)
# print(" ")

# print(">>>>>>>>>>>>>>     Decission Tree      <<<<<<<<<<<<")
# pred = DTmodel.predict(Outless_X_test)
# score = accuracy_score(Outless_y_test,pred)
# print(score)
# conf = confusion_matrix(Outless_y_test,pred)
# print(conf)
# report = classification_report(Outless_y_test,pred)
# print(report)
# print(" ")

# print(">>>>>>>>>>>>>>     Random Forest     <<<<<<<<<<<<")
# pred = RFmodel.predict(Outless_X_test)
# score = accuracy_score(Outless_y_test,pred)
# print(score)
# conf = confusion_matrix(Outless_y_test,pred)
# print(conf)
# report = classification_report(Outless_y_test,pred)
# print(report)
# print(" ")
# print(">>>>>>>>>>>>>>     Logistic Regression     <<<<<<<<<<<<")
# pred = LRmodel.predict(Outless_X_test)
# score = accuracy_score(Outless_y_test,pred)
# print(score)
# conf = confusion_matrix(Outless_y_test,pred)
# print(conf)
# report = classification_report(Outless_y_test,pred)
# print(report)
# print(" ")

In [126]:
y_test.to_numpy()

array([0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1.,
       1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1.,
       0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0.,
       0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 0.,
       1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1.], dtype=float32)

In [127]:
Imputed_X_test

array([[24.,  1.,  4., ...,  1.,  0.,  0.],
       [52.,  4., -1., ...,  1.,  0.,  0.],
       [56.,  2.,  1., ...,  1.,  0.,  0.],
       ...,
       [57.,  2.,  3., ...,  1.,  1.,  0.],
       [59.,  3.,  1., ...,  1.,  1.,  0.],
       [26.,  2., -1., ...,  1.,  0.,  1.]], dtype=float32)

## Scalling Testing Dataset

### Scalling Missing value & Outlier free Testing Dataset

In [128]:
# scale the test dataset
X_test = scaler.transform(Outless_X_test)

X_test.shape, Outless_y_test.shape

((131, 24), (131,))

### Evaluating Model

In [129]:
#Evaluating Model

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print(">>>>>>>>>>>>>>     Support Vector Machine     <<<<<<<<<<<<")
pred = SVCmodel.predict(X_test)
score = accuracy_score(Outless_y_test,pred)
print(score)
conf = confusion_matrix(Outless_y_test,pred)
print(conf) 
report = classification_report(Outless_y_test,pred)
print(report)
print("\n")


# print(">>>>>>>>>>>>>>     Multinomial Naive Bayes     <<<<<<<<<<<<")
# pred = MNBmodel.predict(Outless_X_test)
# score = accuracy_score(Outless_y_test,pred)
# print(score)
# conf = confusion_matrix(Outless_y_test,pred)
# print(conf)
# report = classification_report(Outless_y_test,pred)
# print(report)
# print(" ")

print(">>>>>>>>>>>>>>     Gaussian Naive Bayes     <<<<<<<<<<<<")
pred = GNBmodel.predict(X_test)
score = accuracy_score(Outless_y_test,pred)
print(score)
conf = confusion_matrix(Outless_y_test,pred)
print(conf)
report = classification_report(Outless_y_test,pred)
print(report)
print(" ")

print(">>>>>>>>>>>>>>     Decission Tree      <<<<<<<<<<<<")
pred = DTmodel.predict(X_test)
score = accuracy_score(Outless_y_test,pred)
print(score)
conf = confusion_matrix(Outless_y_test,pred)
print(conf)
report = classification_report(Outless_y_test,pred)
print(report)
print(" ")

print(">>>>>>>>>>>>>>     Random Forest     <<<<<<<<<<<<")
pred = RFmodel.predict(X_test)
score = accuracy_score(Outless_y_test,pred)
print(score)
conf = confusion_matrix(Outless_y_test,pred)
print(conf)
report = classification_report(Outless_y_test,pred)
print(report)
print(" ")
print(">>>>>>>>>>>>>>     Logistic Regression     <<<<<<<<<<<<")
pred = LRmodel.predict(X_test)
score = accuracy_score(Outless_y_test,pred)
print(score)
conf = confusion_matrix(Outless_y_test,pred)
print(conf)
report = classification_report(Outless_y_test,pred)
print(report)
print(" ")

>>>>>>>>>>>>>>     Support Vector Machine     <<<<<<<<<<<<
0.9923664122137404
[[52  1]
 [ 0 78]]
              precision    recall  f1-score   support

         0.0       1.00      0.98      0.99        53
         1.0       0.99      1.00      0.99        78

    accuracy                           0.99       131
   macro avg       0.99      0.99      0.99       131
weighted avg       0.99      0.99      0.99       131



>>>>>>>>>>>>>>     Gaussian Naive Bayes     <<<<<<<<<<<<
0.9236641221374046
[[51  2]
 [ 8 70]]
              precision    recall  f1-score   support

         0.0       0.86      0.96      0.91        53
         1.0       0.97      0.90      0.93        78

    accuracy                           0.92       131
   macro avg       0.92      0.93      0.92       131
weighted avg       0.93      0.92      0.92       131

 
>>>>>>>>>>>>>>     Decission Tree      <<<<<<<<<<<<
0.9618320610687023
[[51  2]
 [ 3 75]]
              precision    recall  f1-score   support

     